# Settings
url: https://lufevida.github.io
baseurl: /html5up-identity
title: Jane Doe
tagline: Senior Psychonautics Engineer
avatar: images/avatar.jpg

# Contact
#email: name@provider.com
#twitter: username
#facebook: username
#instagram: username
#github: username
#dribble: username
#linkedin: username