# Settings
url: https://lufevida.github.io
baseurl: /html5up-identity

# Contact
email: name@provider.com
twitter: username
facebook: username
instagram: username
github: username
dribble: username
linkedin: username